<?php

/**
 * Implements hook_payment_method_controller_info().
 */
function paymill_payment_payment_method_controller_info() {
  return array(
    '\Drupal\paymill_payment\CreditCardController',
    '\Drupal\paymill_payment\AccountController',
  );
}

/**
* Implements hook_libraries_info().
*
* for paymills php wrapper library.
*/
function paymill_payment_libraries_info() {
  $libraries['paymill-php'] = array(
    'name' => 'Paymill',
    'vendor url' => 'https://www.paymill.com/',
    'download url' => 'https://github.com/paymill/paymill-php',
    'version' => '3.0.2',
    'xautoload' => function($api) {
      $api->namespaceRoot('Paymill');
    },
  );
  return $libraries;
}
